<a href="https://colab.research.google.com/github/karthikravi123/pytorch_practice/blob/main/indexing_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pytorch -Indexing Tensors
This will help us efficiently access ,manipulate and analyze data stored intensors



In [1]:
import torch

In [2]:
##accessing elements in a tensor

'''
tensor[row,column]
'''

tensor = torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print(tensor.ndim)

2


In [3]:
print(tensor.shape)

torch.Size([3, 3])


Indexing

In [4]:
print("elements at (0,1)",tensor[0,1])

elements at (0,1) tensor(20)


In [5]:
tensor[0]

tensor([10, 20, 30])

In [6]:
tensor[:,0]

tensor([10, 40, 70])

Slicing

In [10]:
print("first two rows:",tensor[:2])

first two rows: tensor([[10, 20, 30],
        [40, 50, 60]])


In [11]:
print("first two colums",tensor[:,:2])

first two colums tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [13]:
print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [12]:
print(tensor[1,1:3])

tensor([50, 60])


In [16]:
##(0,1)-20 (2,2)-90
tensor[[0,2],[1,2]]

tensor([20, 90])

In [17]:
##boolean indexing

mask = tensor > 50
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [18]:
print(tensor[mask])

tensor([60, 70, 80, 90])


In [19]:
##changing tensor values via indexing

print(tensor)
tensor[0,1] =25
print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [20]:
tensor[:,0] = torch.tensor([100,200,300])

In [21]:
tensor

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])

Advance slicing with source dot index select

In [22]:
indices = torch.tensor([0,2])
selected_rows = torch.index_select(tensor,dim=0,index=indices)
selected_rows

tensor([[100,  25,  30],
        [300,  80,  90]])

In [23]:
indices = torch.tensor([0,2])
selected_rows = torch.index_select(tensor,dim=1,index=indices)
selected_rows

tensor([[100,  30],
        [200,  60],
        [300,  90]])

In [24]:
##using tensor with steps

print(tensor[:,::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [27]:
##using tensor with steps

#print(tensor[::-1])
torch.flip(tensor,dims=(0,))

tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])