<a href="https://colab.research.google.com/github/karthikravi123/pytorch_practice/blob/main/Matrix_Aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix_Aggregation refers to extracting meaningful summaries from matrices or tensors sum ,means etc

In [1]:
import torch

In [2]:
matrix =torch.tensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])

In [3]:
matrix

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [4]:
print(matrix.sum())

tensor(45.)


In [6]:
print(matrix.mean())
print(matrix.max())
print(matrix.min())
print(matrix.median())

tensor(5.)
tensor(9.)
tensor(1.)
tensor(5.)


In [8]:
##dim=0 --rows --columns
#dim=1 --col --across row
print(matrix.max(dim=0))
print(matrix.sum(dim=0))

torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
tensor([12., 15., 18.])


In [9]:
matrix.cumsum(dim=1)

tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.],
        [ 7., 15., 24.]])

In [11]:
matrix.cumprod(dim=0)

tensor([[  1.,   2.,   3.],
        [  4.,  10.,  18.],
        [ 28.,  80., 162.]])

In [14]:
##adance aggregration

masked_matrix_sum = matrix[matrix>8].sum()
masked_matrix_sum

tensor(9.)

In [17]:
matrix =torch.tensor([[0.,0.,0.],[4.,5.,6.],[7.,8.,9.]])

In [18]:
matrix.nonzero()

tensor([[1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])

In [19]:
matrix.nonzero().size()

torch.Size([6, 2])

In [20]:
#normalized matirx

In [21]:
matrix =torch.tensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])



In [23]:
max_v = matrix.max()
min_v = matrix.min()
##normalization

normalized_matrix = (matrix-  min_v)/(max_v - min_v)

In [24]:
normalized_matrix

tensor([[0.0000, 0.1250, 0.2500],
        [0.3750, 0.5000, 0.6250],
        [0.7500, 0.8750, 1.0000]])