<a href="https://colab.research.google.com/github/karthikravi123/pytorch_practice/blob/main/Stack_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])
print(tensor_1.ndim)
print(tensor_1.size())

1
torch.Size([3])


In [5]:
stacked_tenspr_dim_0 = torch.stack((tensor_1,tensor_2),dim=0)
print(stacked_tenspr_dim_0.shape)
print(stacked_tenspr_dim_0)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
stacked_tenspr_dim_0 = torch.stack((tensor_1,tensor_2),dim=1)
print(stacked_tenspr_dim_0.shape)
print(stacked_tenspr_dim_0)

torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [8]:
tensor_3 = torch.tensor([7,8,9])
stacked_tenspr_dim_0 = torch.stack((tensor_1,tensor_2,tensor_3),dim=1)
stacked_tenspr_dim_0


tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [10]:
##stacking 2D tensors

tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

stack1 = torch.stack((tensor1,tensor2),dim=0)
stack1

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [11]:
stack1 = torch.stack((tensor1,tensor2),dim=1)
stack1

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

In [14]:
stack1 = torch.stack((tensor1,tensor2),dim=2)
stack1

tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])

Concatenation operation

In [17]:
torch.cat((tensor1,tensor2),dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [18]:
torch.cat((tensor1,tensor2),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])