<a href="https://colab.research.google.com/github/karthikravi123/pytorch_practice/blob/main/Tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensor Manipulation

Tensor manipulation operation include  

* reshaping  
* slicing  
* joining or splitting  
* transposing and permuting dimension  

reshaping -two techniques reshape or view

In [1]:
import torch

In [2]:
original_tensor = torch.arange(12)
original_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
##reshaping tensor

original_tensor.nelement()

12

In [5]:
original_tensor.ndim

1

In [6]:
#2x6 =12

reshaped_tensor = original_tensor.reshape(2,6)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

2
12


In [7]:
reshaped_tensor = original_tensor.reshape(3,4)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

2
12


dimension automatically calcualted by pytorch,create vector

In [12]:
##view
##original_tensor should be contigous -it is in a sequence in a memeory
flattened_tensor = original_tensor.view(-1)
flattened_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
print(original_tensor.is_contiguous())
flattened_tensor = original_tensor.view(-1)
flattened_tensor

True


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##Slicing  

Extract specific portion of tensor

In [13]:
tensor_a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
tensor_a.ndim

2

In [15]:
tensor_a.ndimension

<function Tensor.ndimension>

In [16]:
tensor_a[0]

tensor([1, 2, 3])

In [18]:
tensor_a[:,0]

tensor([1, 4, 7])

In [19]:
tensor_a[1:,1:]

tensor([[5, 6],
        [8, 9]])

#joining tensor

In [21]:
##torch.cat()--> merges tensors along and existing dimension

tensor1 =torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[4,5],[6,7]])
contcat_tensor_row =torch.cat((tensor1,tensor2),dim=0)
contcat_tensor_col =torch.cat((tensor1,tensor2),dim=1)
print(contcat_tensor_row,"\n",contcat_tensor_col)

tensor([[1, 2],
        [3, 4],
        [4, 5],
        [6, 7]]) 
 tensor([[1, 2, 4, 5],
        [3, 4, 6, 7]])


#stack -->created a new_dimension ,increases the tensor rank

In [22]:
##torch.cat()--> merges tensors along and existing dimension

tensor1 =torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[4,5],[6,7]])
stack_tensor_row =torch.stack((tensor1,tensor2),dim=0)
stack_tensor_col =torch.stack((tensor1,tensor2),dim=1)
print(stack_tensor_row,"\n",stack_tensor_col)

tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]]) 
 tensor([[[1, 2],
         [4, 5]],

        [[3, 4],
         [6, 7]]])


#splitting

- torch.chunk() -->divides tensor into equal size chunks

- torch.split() --> allows uneven splitting based on size

In [23]:
original_tensor = torch.arange(12)

chunks = torch.chunk(original_tensor,3,dim=0)
print(chunks)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))


In [27]:
original_tensor = torch.arange(13)

chunks = torch.chunk(original_tensor,5,dim=0)
print(chunks)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]), tensor([12]))


In [26]:
for chunk  in chunks:
  print(chunk)

tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [28]:
original_tensor = torch.arange(13)

split = torch.split(original_tensor,5,dim=0)
print(split)

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11, 12]))


In [29]:
for splits  in split:
  print(splits)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11, 12])


Transposing and premuting

--transpose() -->swaps two dimension.
m x n --> n x m

-- permute() - rearranges all dimenstion in the specified order

In [35]:
tensor_original = torch.arange(24).reshape(12,2)
print(tensor_original)
tensor_original.transpose(0,1)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])


tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

In [32]:
tensor_original = torch.arange(24).reshape(2,3,4)
print(tensor_original)
#[0,1,2]
permute_tensor = tensor_original.permute(2,0,1)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [36]:
l =[0,1,2,3,4]
[4,1,2,3,0]


[4, 1, 2, 3, 0]

Cloning and detaching

In [37]:
#3sepearate copy
import copy
a =[1,2,3]
b = copy.deepcopy(a)
print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [38]:
tensor = torch.ones(3,3,requires_grad =True)
clone_tensor =tensor.clone()
clone_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], grad_fn=<CloneBackward0>)

In [39]:
tensor.detach() ##this code wil detach tensor form computation graph

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])