<a href="https://colab.research.google.com/github/karthikravi123/pytorch_practice/blob/main/ViewandReshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

view() and reshape() are used to change the shape of tensors,
The core idea is to transform a tensor into a new shape while keeping the data consistent

View - contigous data in memory

reshape - more flexibility

Contiguous
orignal: [[1,2,3],[4,5,6]] = 2 x 3
in-memory :  [1,2,3,4,5]

Non-contigous

original data: [[1,2,3],[4,5,6]]

transposed data : [[1,4],[2,5],[3,6]]

IN-memory: [1,2,3,4,5,6]

The data remains the same in memory but the access pattern changes


low performance comapred to contigous data

Reshape - non contigous data

it creates copy of data of contingous data

Reshape works with both contigous and non contigous data

In [1]:
import torch

In [2]:
tensor= torch.arange(12)

In [3]:
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
reshaped_tensor_view = tensor.view(2,6)
reshaped_tensor_reshape = tensor.reshape(2,6)

In [5]:
reshaped_tensor_view

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [6]:
reshaped_tensor_reshape

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [7]:
tensor.is_contiguous()

True

In [9]:
##3 rows and not shure how amny column we get in new tensor ,it will automatically calcualte it
inferred_shape = tensor.view(3,-1)
print(inferred_shape)
print(inferred_shape.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [13]:
tensor_3d = torch.arange(24).reshape(2,3,4)
tensor_3d

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [14]:
##i want only 1D ,ask pytorch to calcuate wt will be optimal value willl be present

flattened = tensor_3d.view(-1)
print(flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [15]:
flattened.is_contiguous()

True

In [17]:
tensor_2d = torch.arange(24).reshape(12,2)
transpose_tensor = tensor_2d.t()
transpose_tensor

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

In [19]:
transpose_tensor.is_contiguous()

False

In [22]:
error = transpose_tensor.reshape(6,4)

In [23]:
error

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])

In [21]:
transpose_tensor.reshape(-1)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22,  1,  3,  5,  7,  9, 11,
        13, 15, 17, 19, 21, 23])